apiVersion: v1
kind: ServiceAccount
metadata:
    name: db-engineering-sa
    namespace: db-engineering
    annotations:
        iam.gke.io/gcp-service-account: dev-db-engineering-sa@fluent-fortress-497419-c5.iam.gserviceaccount.com