apiVersion: v1
kind: ServiceAccount
metadata:
    name: devops-sa
    namespace: devops
    annotations:
        iam.gke.io/gcp-service-account: dev-devops-sa@fluent-fortress-497419-c5.iam.gserviceaccount.com