apiVersion: v1
kind: ResourceQuota
metadata:
  name: db-engineering-quota
  namespace: db-engineering
spec:
  hard:
    pods: "20"
    requests.cpu: "4"
    requests.memeory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"