apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hrm-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec: 
  project: hrm-platform

  source:
    repoURL: https://github.com/Y3GI/high_availability_hrm/
    targetRevision: main
    path: k8s/apps/hrm/
    helm:
      valueFiles: 
        - values.yaml

  destinations:
    server: https://kubernetes.default.svc
    namespace: hrm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground