apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hrm-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "{{ .Values.namespace }}-ingress-ip"
    networking.gke.io/managed-certificates: "hrm-cert"
spec:
  rules:
    - host: {{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hrm-service
                port:
                  number: 80
