apiVersion: v1
kind: Service
metadata: 
  name: hrm-service
  namespace: {{ .Values.namespace }}
  annotations: 
    cloud.google.com/backend-config: '{"default": "hrm-iap-config"}'
spec:
  selector:
    app: hrm
  ports:
    - port: 80
      targetPort: 8080
  type: NodePort