# .github/workflows/build-images.yml
name: Build & Push Images

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Type "Deploy HRM" to confirm the destruction of the environment'
                required: true
                default: 'NO'

permissions:
    id-token: write
    contents: read

env:
    GOOGLE_CLOUD_PROJECT: ${{ vars.GOOGLE_CLOUD_PROJECT }}
    GOOGLE_REGION: ${{ vars.GOOGLE_REGION }}

jobs:
    build:
        name: Deploy HRM app
        runs-on: ubuntu-latest
        if: github.event.inputs.environment == 'Deploy HRM'

        steps:
            - uses: actions/checkout@v4
            
            - name: Authenticate to GCP
              uses: google-github-actions/auth@v2
              with:
                workload_identity_provider: ${{ secrets.GOOGLE_WIF_PROVIDER }}
                service_account: ${{ secrets.GOOGLE_SA_EMAIL }}
            
            - name: Configure Docker
              run: gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet
            
            - name: Build and push HRM app
              run: |
                IMAGE=europe-west4-docker.pkg.dev/${{ env.GOOGLE_CLOUD_PROJECT }}/hrm/hrm-app
                SHA=${{ github.sha }}
                docker build -t $IMAGE:$SHA -t $IMAGE:latest ./hrm_app
                docker push $IMAGE:$SHA
                docker push $IMAGE:latest